#!/usr/bin/env zsh

# Run the keys script and capture its output
submap=$(cat /tmp/binds)
keys_output=$($HOME/.config/hypr/scripts/keys "$submap")

# Check if keybinds window is currently open before closing
if [[ -z "$keys_output" ]]; then
    # Check if the keybinds window exists before trying to close it
    if eww list-windows | grep -q "keybinds"; then
        eww close keybinds
    fi
    exit 0
else
    eww open keybinds
fi

# Parse the output and transform each line
output=$(echo "$keys_output" | while read -r line; do
    # Split the line into fields
    fields=(${(s: :)line})

    # Remove brackets from the first field
    key=${fields[1]//[()]/}

    # Create the output format for each line
    echo "(box :orientation \"v\" :spacing 1 (label :class \"key\" :text \"$key\") (label :class \"action\" :text \"${fields[2,]}\"))"
done | tr -d '\n')

# Print or further process the transformed output as needed
eww update submap="(box :class \"genwin\" :vexpand \"true\" :hexpand \"false\" :spacing 2 (label :halign \"start\" :class \"map\" :text \"${submap}\") ${output})"
