
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$direnv\
$nix_shell\
$python\
$elixir\
$haskell\
$julia\
$rust\
$rlang\
$typst\
$status\
$character\
"""
# A continuation prompt that displays two filled-in arrows
continuation_prompt = '+ '


[directory]
style = "fg:#21BFC2"

[character]
success_symbol = "[](purple)"
error_symbol = "[](red)"

[git_branch]
format = "[$branch]($style)"
style = "fg:#F09383"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style) "
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[python]
symbol = ""
format = "[$virtualenv]($style) "
style = "bright-black"

[elixir]
symbol = "🔮"
style = "fg:#E95678"
format = '[\[$symbol ($version)\]]($style) '

[haskell]
symbol = ""
style = "fg:#E95678"
format = '[\[$symbol ($version)\]]($style) '

[julia]
symbol = ""
style = "fg:#E95678"
format = '[$symbol ($version)]($style) '

[rust]
symbol = ""
style = "fg:#E95678"
format = '[$symbol]($style) '

[rlang]
symbol = "󰰟"
style = "fg:#E95678"
format = '[\[$symbol $version\]]($style) '

[typst]
symbol = "t"
style = "fg:#E95678"
format = '[$symbol]($style) '


[direnv]
symbol = ""
format = '[$symbol$loaded$allowed]($style) '
style = "fg:#FAB795"
disabled = false
allowed_msg = ""
loaded_msg = ""
not_allowed_msg = ""
denied_msg = ""
unloaded_msg = ""

[nix_shell]
disabled = true

[status]
symbol = ""
format = '[$symbol]($style)'
not_executable_symbol = "[$symbol](red)"
not_found_symbol = "[$symbol](orange)"
sigint_symbol = "[$symbol](black)"
signal_symbol = "[$symbol](white)"
disabled = false
