#!/usr/bin/env zsh

set -e

TIMESTAMP=$(date +%d-%m-%Y-%Hh%m)

go () {
  ffmpeg -y \
    -f x11grab \
    -framerate 60 \
    -s 2560x1440 \
    -i :0.0 \
    -f alsa \
    -i default \
    -r 30 \
    -c:v libx264rgb \
    -crf 0 \
    -preset ultrafast \
    -c:a flac \
    "/home/aloysius/Videos/Games/desktop-$TIMESTAMP.mkv" 1>/dev/null 2>&1 &
  set RECORDING=$!
}

kill () {
  pkill ffmpeg
}


case "$1" in
  stop) kill;;
  *)    go;;
esac
